### ISSUE TITLE
Avoid breaking changes to seraiization payloads (category, product attributes etc.)

### ISSUE THREAD

**Issue by AndreasA** [sulu/SuluSyliusProducerPlugin#47]
As one has to implement the Sulu consumer adapters manually, meaning how e.g. products are stored, changes to the payload have impacts not just here but also on the other side and require changes to the custom implementation.
In order to avoid issues there, please add deprecations instead and keep the old payload in addition to the new payloads until a at least the next minor version and only remove it afterwards.
Yes, I know the producer/consumer is still in the `0.x` version stage, but it would be helpful for all who already use it.

Also I am not sure, how helpful the new category behavior is, as e.g. the taxon subscriber https://github.com/sulu/SuluSyliusProducerPlugin/blob/0.x/src/EventSubscriber/TaxonEventSubscriber.php#L48 does not even take into account that all parents are synchronized as well, if a category is changed. Also depending on the adapter changes to the parent category can have impacts on all child categories as well, e.g. URL changes.

**Comment by AndreasA** [comment]
Just to be clear. this is more an information that some things can be breaking changes, even though one doesn't expect them to be and at least require an entry in the upgrade.md

I also know that determining all breaking changes isn't always that easy, so it definitely can happen that there is a breaking change without documentation. This issue should just list additional potential breaking changes, so they can be taken into account, either by avoiding them or adding documentation for it.

There probably will be similar issues in the future as one cannot take into account everything, but the more potential issues, one knows, the easier it is to notice them 😄

**Comment by AndreasA** [comment]
As discussed in our meeting. I am closing this as you try to avoid this anyway and you now know about the BC break regarding attributes.

**Comment by wachterjohannes** [comment]
@AndreasA as always we want to keep track on all the BC-Breaks we introduce in ever PR. The change of the communication payload seems to be a valid case to create an entry in the UPGRADE.md - BUT there were no usage of this values in the consumer - so we saw no need to document that.

As you already mentioned we discussed that in a call and we will try to keep track about that changes in the future
